[[Qt6Base]]
arch = "aarch64"
git-tree-sha1 = "1247750a0cc2737b2ab44d0b05442ec3679c0046"
os = "macos"

    [[Qt6Base.download]]
    sha256 = "6cc82ac62e3a30f59b13ec98cb6cf714b52834ea40a70583dd782839bae2b083"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.aarch64-apple-darwin.tar.gz"
[[Qt6Base]]
arch = "x86_64"
git-tree-sha1 = "c640a4b048d6172d817653cb8380dfb63698cda3"
os = "macos"

    [[Qt6Base.download]]
    sha256 = "bb70114574cf60bb17a34acc7ec00b1b5d363cf1d814f2414105f1e277d44c30"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.x86_64-apple-darwin.tar.gz"
[[Qt6Base]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ff4543c4cd4fe0a845a27dd9e7ac18254349946"
os = "windows"

    [[Qt6Base.download]]
    sha256 = "e470db32e42eeca6bfe3f69999fa5409b511a9ee00a6de69065f92a6d16491b9"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.i686-w64-mingw32-cxx11.tar.gz"
[[Qt6Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d59e9109f6cc8a99f06c2767b4ad3272b5cf7991"
os = "windows"

    [[Qt6Base.download]]
    sha256 = "ec7964c6653b0f5e3c10dce8c6f16dbfa11db09f8582342fb0f75c3c8280ccca"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt6Base]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59cb99dd9f08ed5bcced6cae357131f4b4c7c195"
libc = "glibc"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "ddc186a9beec2910453946e6cb8120e2513cda355643af2a423e583c501cdd5a"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt6Base]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b7f4273cbf0ba30e37cc970d2b930e2e2143d5d"
libc = "musl"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "58f535395e27f802cf689d2f180c804cc3f877874102f07e3b188578689eead6"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.aarch64-linux-musl-cxx11.tar.gz"
[[Qt6Base]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dffbc5a7c9e08ec70438f3ac6ef338bfa0f17f6d"
libc = "glibc"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "0b7f3be9f9da08d6c40f653c5d0517b055be98e567d3ba7e0c478b2018a1205b"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt6Base]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4adbb5a07ffbf7aaf0b5aba9ab39b18e8293ebc"
libc = "musl"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "fd7545b65c7425a9c494fa5e5eb182081246c8300a07be49fa498ee0e566705f"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Qt6Base]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc6ea1ae00dc729b491e1dc341bfbbb307d635c1"
libc = "glibc"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "da0a004b6758527b62ceadccd848373530b263f601b79d2266a1f1ead4a9bc53"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.i686-linux-gnu-cxx11.tar.gz"
[[Qt6Base]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b4d0869bf898c5aba91b58c4eb7f8a867d09dc9"
libc = "musl"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "e8b9f3744031c0463fc24ccf7f0a96947e037978f7ecf5601a527c80df7bbc1c"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.i686-linux-musl-cxx11.tar.gz"
[[Qt6Base]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3de6a62516e9f7f903e183b746743a064512e7a7"
libc = "glibc"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "1a1871b23016632828922c2f7cf5d7324779de66d642b21cfd04ec53766ea23b"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt6Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48d95e60ccfecd4622b42d4fbeda49b2cbc7530b"
libc = "glibc"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "b6aea7fe6c2a1f6682be8e7881d88d54d91342aab104c47efdf72c390c0b82a1"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt6Base]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16acc4dc74ee524d6f74671cf4496b063a3a5898"
libc = "musl"
os = "linux"

    [[Qt6Base.download]]
    sha256 = "f5ba8a955b207d06805ef45b9f19204cc03e05ee3280c586b7940a25c7403763"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.x86_64-linux-musl-cxx11.tar.gz"
[[Qt6Base]]
arch = "x86_64"
git-tree-sha1 = "e44a40028ea869e305bf8aa2db0e7f4efb8cef8e"
os = "freebsd"

    [[Qt6Base.download]]
    sha256 = "7d0c414334af3f5859f9969daf81dc4be302f39e65897a937abc81e8212ee028"
    url = "https://github.com/JuliaBinaryWrappers/Qt6Base_jll.jl/releases/download/Qt6Base-v6.10.2+2/Qt6Base.v6.10.2.x86_64-unknown-freebsd.tar.gz"
